# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: maprover-api-visualization
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  stage: prod
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

#you can add packaging information here
package:
  individually: true

functions:
  api-describe:
    runtime: nodejs12.x
    handler: describe.inferHandler
    package: 
      include:
        - lib/**
        - api-gateway-models/**
    events:
      - http:
          path: api/describe
          method: get
          cors: true
          private: false
          documentation:
            summary: "Returns description of endpoints"
            description: "Returns description of endpoints. Format: class-name: [name, relative endpoint]"
            tags:
              - "Api"
              - "Visualization"

# you can add CloudFormation resource templates here
resources:
  Resources:
    tileInputValidator:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'tileInputValidator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

plugins:
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-plugin-custom-roles
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'visualization.api.maprover.io'
    stage: ${self:provider.stage}
    basePath: ''
    certificateName: '*..api.maprover.io'
    createRoute53Record: false
    endpointType: 'edge'
    securityPolicy: 'tls_1_2'
    apiType: 'rest'
    enabled: fale
  documentation:
    api:
      info:
        version: "v0.0.1"
        title: "Maprover API"
        description: "Maprover Visualization API"
