# serverless.yml

service: apollo-lambda-covid-19
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
plugins:
  - serverless-domain-manager
custom:
  customDomain:
    domainName: 'visualization.api.maprover.io'
    stage: ${self:provider.stage}
    basePath: ''
    certificateName: '*.api.maprover.io'
    createRoute53Record: false
    endpointType: 'edge'
    securityPolicy: 'tls_1_2'
    apiType: 'rest'
    enabled: true